version: '3.8'

services:
  app:
    restart: always
    container_name: mohaeng-server
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPOSITORY_NAME}:${IMAGE_TAG}
    ports:
      - 8080:8080
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 800M
