spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao_client_id}
            redirect-uri: ${kakao_redirect_uri}
            client-authentication-method: POST
            client-secret: ${kakao_client_secret}
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  token:
    secret-key: ${jwt_secret_key}
  access-token:
    expire-length: ${jwt_access_token_expire_length}
  refresh-token:
    expire-length: ${jwt_refresh_token_expire_length}